version: "3.3"
services:
        node:
                image: "node:14.15.1-alpine3.12"
                ports:
                        - "3000:3000"
                working_dir: /project
                command: ash -c "npm install nodemon -g && npm install && npm start"
                volumes:
                        - .:/project
                depends_on:
                        - openldap
                        - redis
                networks:
                        - my_network

        ldap_server:
                image: "node:14.15.1-alpine3.12"
                ports:
                        - "1389"
                working_dir: /ldap
                command: ash -c "node ldapServer.js"
                volumes:
                        - /home/jhcheng/Desktop/ldapJStest/ldapTest:/ldap
                networks:
                        - my_network

        openldap:
                image: "osixia/openldap:latest"
                ports: 
                        - "8380:389"
                working_dir: /data
                command: ash -c "ldapadd -H ldap://ldap_server:1389 -D cn=root -w secret -f qwer.ldif"
                volumes:
                        - type: bind
                          source: /home/jhcheng/Desktop/ldapJStest/ldapTest/qwer.ldif
                          target: /data/qwer.ldif
                depends_on: 
                        - ldap_server
                networks:
                        - my_network

        redis:
                image: "redis:4.0.9-alpine"
                ports:
                        - "6379"
                networks:
                        - my_network

networks:
        my_network:
                external:
                        name: open_banking_network
